### PR TITLE
Updates defaults/main.yml to include flameshot package.

### PR DESCRIPTION
**Pull request by sei-dspooner**
Adds Flameshot package.

# 

## 🗣 Description

Flameshot is required to create annotations and pixelated obfuscations on screenshots.

## 💭 Motivation and Context

This adds a new base package to the image.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jsf9k** [comment]
Thanks for the contribution @sei-dspooner!

We currently have an issue where our automated tests fail because of a very recent change in [ansible-community/molecule].  Once we fix that then the tests for your PR should pass, and then we can merge it.

**Review by jsf9k — APPROVED** [review]
Once the recent breaking change from molecule is resolved and the tests pass, this pull request should be good to be merged.

Thanks again for the PR @sei-dspooner!

**Review by dav3r — APPROVED** [review]
LGTM - thanks @sei-dspooner for the contribution! 🔥

**Comment by jsf9k** [comment]
The test workflow is failing because GitHub does not allow secrets to be passed to workflows for pull requests generated from a fork.

**Pull request merged**
